name: afaci

services:
  frontend:
    build:
      dockerfile: Dockerfile
      args:
        BACKEND_URL: http://backend:8000
    restart: unless-stopped
    environment:
      BACKEND_URL: http://backend:8000
    ports:
      - "${FRONTEND_PORT:-86}:3000"
    networks:
      - afaci-network
volumes:
  afaci-pgdata:
networks:
  afaci-network:
    driver: bridge
