name: base-ci-frontend

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

permissions:
  contents: read

jobs:  
  frontend-analysis:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
  
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: './package-lock.json'
  
      - run: npm ci
      - run: npx eslint .
      - run: npx prettier --check .
      - run: npx tsc --noEmit
      
  build:
    name: build
    runs-on: afaci-runner-01
    needs:
      - frontend-analysis
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
    
      - run: docker build -t ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }} .
      - run: docker save ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }} -o image.tar
      
      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v6
        with:
            name: docker-image
            path: image.tar
            retention-days: 1

  image-push:
    runs-on: afaci-runner-01
    needs: build
    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v6
        with:
          name: docker-image

      - run: docker load -i image.tar
      - run: echo "${{ secrets.NEXUS_PASSWORD }}" | docker login ${{ secrets.NEXUS_REGISTRY }} -u "${{ secrets.NEXUS_USER }}" --password-stdin
      - run: docker push ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}

      - name: Log out from Nexus
        if: always()
        run: docker logout ${{ secrets.NEXUS_REGISTRY }}

  deploy:
    runs-on: afaci-runner-01
    needs: image-push
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - run: echo "${{ secrets.NEXUS_PASSWORD }}" | docker login ${{ secrets.NEXUS_REGISTRY }} -u "${{ secrets.NEXUS_USER }}" --password-stdin

      - name: Deploy to devops-server (external daemon)
        env:
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
          BACKEND_IMAGE: ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          BACKEND_PORT: ${{ secrets.BACKEND_PORT || '8000' }}
        run: |
          pwd
          ls -la
          docker compose -f - up -d --pull always < docker-compose.yml  
    
    
